language: php

php:
- 7.2
- 7.3

install:
- composer install --prefer-dist --no-interaction --no-suggest

script:
- composer stan
- vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
- bash <(curl -s https://codecov.io/bash)
